In [1]:
import pandas as pd

In [13]:
from surprise import Reader
from surprise import Dataset
from surprise.model_selection import cross_validate
from surprise import NormalPredictor
from surprise import KNNBasic
from surprise import KNNWithMeans
from surprise import KNNWithZScore
from surprise import KNNBaseline
from surprise import SVD
from surprise import BaselineOnly
from surprise import SVDpp
from surprise import NMF
from surprise import SlopeOne
from surprise import CoClustering
from surprise.accuracy import rmse
from surprise import accuracy
from surprise.model_selection import train_test_split

In [3]:
df_ratings = pd.read_csv('./data/movie/ratings_join.csv',engine='python', thousands=',')

In [4]:
del df_ratings["Unnamed: 0"]

In [5]:
df_ratings

,userId,movieId,rating,timestamp,title
0,1,110,1.0,1425941529,Three Colors: Red
1,1,147,4.5,1425942435,The 400 Blows
2,1,858,5.0,1425941523,Sleepless in Seattle
3,1,1246,5.0,1425941556,Rocky Balboa
4,1,1968,4.0,1425942148,Fools Rush In
5,1,2762,4.5,1425941300,Young and Innocent
6,1,2959,4.0,1425941601,License to Wed
7,1,4226,4.0,1425942228,Shriek If You Know What I Did Last Friday the ...
8,1,54503,3.5,1425941313,The Mystery of Chess Boxing
9,1,58559,4.0,1425942007,Confession of a Child of the Century
10,1,96821,5.0,1425941382,Caesar Must Die
11,2,5,3.0,867039249,Four Rooms
12,2,25,3.0,867039168,Jarhead
13,2,58,3.0,867039325,Pirates of the Caribbean: Dead Man's Chest
14,2,64,4.0,867039612,Talk to Her
15,2,79,4.0,867039325,Hero
16,2,141,3.0,867039168,Donnie Darko
17,2,260,4.0,867039249,The 39 Steps
18,2,339,5.0,867041296,Night on Earth
19,2,377,4.0,867041121,A Nightmare on Elm Street
20,2,605,4.0,867039973,The Matrix Revolutions
21,2,628,4.0,867039325,Interview with the Vampire
22,2,648,4.0,867039167,Beauty and the Beast
23,2,762,3.0,867039325,Monty Python and the Holy Grail
24,2,780,3.0,867039165,The Passion of Joan of Arc
25,2,786,1.0,867039249,Almost Famous
26,2,788,1.0,867039288,Mrs. Doubtfire
27,2,1552,2.0,867040735,Parenthood
28,3,480,3.0,1048076925,Monsoon Wedding
29,3,500,2.0,1048076945,Reservoir Dogs
...,...,...,...,...,...
11437607,270896,4896,4.0,1257031820,Muxm채uschenstill
11437608,270896,4973,5.0,1257031597,Under the Sand
11437609,270896,4979,4.5,1257033785,Windows on Monday
11437610,270896,4993,5.0,1257031464,5 Card Stud
11437611,270896,4995,5.0,1257031503,Boogie Nights
11437612,270896,5618,4.5,1257034014,"Cousin, Cousine"
11437613,270896,5816,4.0,1257031810,Waiter
11437614,270896,5902,4.5,1257034264,A Bridge Too Far
11437615,270896,5991,4.0,1257034257,The Last Laugh
11437616,270896,5995,5.0,1257034431,Miffo
11437617,270896,6016,4.0,1257034275,The Good Thief
11437618,270896,8368,4.0,1257031745,The Garden of Eden
11437619,270896,8665,4.0,1257031889,K-19: The Widowmaker
11437620,270896,8874,4.5,1257033950,My Best Friend's Wedding
11437621,270896,8961,3.5,1257033870,Bad Boys II
11437622,270896,30707,5.0,1257034200,Star 80
11437623,270896,30793,3.5,1257033981,House of Dracula
11437624,270896,33166,4.5,1257034186,Downhill Racer
11437625,270896,40815,4.0,1257032001,On Guard
11437626,270896,40819,4.0,1257034287,Best Worst Movie
11437627,270896,41566,3.5,1257034128,New York Doll
11437628,270896,44191,5.0,1257031546,Loose Screws
11437629,270896,45722,3.5,1257031715,Don't Look Down
11437630,270896,46578,4.5,1257034037,Cheerleaders' Wild Weekend
11437631,270896,48385,4.0,1257031939,Indestructible Man
11437632,270896,48780,5.0,1257031830,Boat
11437633,270896,49530,4.0,1257034436,In Time
11437634,270896,54001,4.0,1257034331,The Traveler
11437635,270896,54503,4.0,1257033886,The Mystery of Chess Boxing
11437636,270896,58559,5.0,1257031564,Confession of a Child of the Century

In [6]:
df_ratings["rating"].unique()

array([1. , 4.5, 5. , 4. , 3.5, 3. , 2. , 2.5, 1.5, 0.5])

In [7]:
del df_ratings['timestamp']

In [8]:
df_ratings.iloc[:,:3]

          userId  movieId  rating
0              1      110     1.0
1              1      147     4.5
2              1      858     5.0
3              1     1246     5.0
4              1     1968     4.0
5              1     2762     4.5
6              1     2959     4.0
7              1     4226     4.0
8              1    54503     3.5
9              1    58559     4.0
10             1    96821     5.0
11             2        5     3.0
12             2       25     3.0
13             2       58     3.0
14             2       64     4.0
15             2       79     4.0
16             2      141     3.0
17             2      260     4.0
18             2      339     5.0
19             2      377     4.0
20             2      605     4.0
21             2      628     4.0
22             2      648     4.0
23             2      762     3.0
24             2      780     3.0
25             2      786     1.0
26             2      788     1.0
27             2     1552     2.0
28             3      480     3.0
29             3      500     2.0
...          ...      ...     ...
11437607  270896     4896     4.0
11437608  270896     4973     5.0
11437609  270896     4979     4.5
11437610  270896     4993     5.0
11437611  270896     4995     5.0
11437612  270896     5618     4.5
11437613  270896     5816     4.0
11437614  270896     5902     4.5
11437615  270896     5991     4.0
11437616  270896     5995     5.0
11437617  270896     6016     4.0
11437618  270896     8368     4.0
11437619  270896     8665     4.0
11437620  270896     8874     4.5
11437621  270896     8961     3.5
11437622  270896    30707     5.0
11437623  270896    30793     3.5
11437624  270896    33166     4.5
11437625  270896    40815     4.0
11437626  270896    40819     4.0
11437627  270896    41566     3.5
11437628  270896    44191     5.0
11437629  270896    45722     3.5
11437630  270896    46578     4.5
11437631  270896    48385     4.0
11437632  270896    48780     5.0
11437633  270896    49530     4.0
11437634  270896    54001     4.0
11437635  270896    54503     4.0
11437636  270896    58559     5.0

[11437637 rows x 3 columns]

In [11]:
df_new = df_ratings.copy()

In [12]:
del df_new['title']

In [13]:
df_new.shape[0]

11437637

In [30]:
from surprise import Dataset
from surprise import NormalPredictor
from surprise import Reader
from surprise.model_selection import cross_validate
import pandas as pd
import numpy as np

In [31]:
# A reader is still needed but only the rating_scale param is requiered.
reader = Reader(rating_scale=(0, 5))

# The columns must correspond to user id, item id and ratings (in that order).
data = Dataset.load_from_df(df_new[['userId', 'movieId', 'rating']], reader)

In [34]:
import surprise

In [35]:
from surprise.model_selection import KFold

In [36]:
bsl_param = {'method':'als','n_epochs':5,'reg_u':12,'reg_i':5}
model = surprise.BaselineOnly(bsl_options=bsl_param)

In [37]:
acc = np.zeros(3)
cv = KFold(3)
for i ,(trainset, testset) in enumerate(cv.split(data)):
    model.fit(trainset)
    pred = model.test(testset)
    acc[i] = surprise.accuracy.rmse(pred,verbose=True)
acc.mean()

Estimating biases using als...
RMSE: 0.8814
Estimating biases using als...
RMSE: 0.8810
Estimating biases using als...
RMSE: 0.8817

0.8813644678618807

In [38]:
cross_validate(model,data)

Estimating biases using als...
Estimating biases using als...
Estimating biases using als...
Estimating biases using als...
Estimating biases using als...

{'test_rmse': array([0.87955919, 0.87947445, 0.87936861, 0.87964097, 0.87914872]),
 'test_mae': array([0.67728296, 0.67729374, 0.67742712, 0.67764829, 0.67731312]),
 'fit_time': (23.999810934066772,
  29.483141899108887,
  29.52238154411316,
  29.503634214401245,
  30.711968660354614),
 'test_time': (18.593157529830933,
  14.674648761749268,
  19.49369788169861,
  15.324353218078613,
  22.696009874343872)}

In [10]:
import pandas as pd
from surprise import Reader
from surprise import Dataset
from surprise.model_selection import cross_validate
from surprise import NormalPredictor

In [14]:
reader = Reader(rating_scale=(0, 9))
data = Dataset.load_from_df(df_new[['userId', 'movieId', 'rating']], reader)

In [15]:
data

In [ ]:
SVD(), SVDpp(), SlopeOne(), NMF(), NormalPredictor(), KNNBaseline(), KNNBasic(), KNNWithMeans(), KNNWithZScore(), BaselineOnly(), CoClustering()

In [18]:
benchmark = []
# Iterate over all algorithms
for algorithm in [SVD(), SVDpp()]:
    # Perform cross validation
    results = cross_validate(algorithm, data, measures=['RMSE'], cv=3, verbose=True)
    
    # Get results & append algorithm name
    tmp = pd.DataFrame.from_dict(results).mean(axis=0)
    tmp = tmp.append(pd.Series([str(algorithm).split(' ')[0].split('.')[-1]], index=['Algorithm']))
    benchmark.append(tmp)
    
pd.DataFrame(benchmark).set_index('Algorithm').sort_values('test_rmse')

Evaluating RMSE of algorithm SVD on 3 split(s).

                  Fold 1  Fold 2  Fold 3  Mean    Std
RMSE (testset)    0.8454  0.8453  0.8451  0.8452  0.0001
Fit time          479.49  491.39  466.78  479.22  10.05
Test time         52.71   56.32   55.68   54.90   1.57

KeyboardInterrupt:

In [ ]:
 SVD(), SVDpp(), SlopeOne(), NMF(), NormalPredictor(), KNNBaseline(), KNNBasic(), KNNWithMeans(), KNNWithZScore(), BaselineOnly(), CoClustering()

In [ ]:
import matplotlib.pyplot as plt
%matplotlib inline

In [ ]:
plt.figure(figsize=(15,15))
plt.imshow(dt_ratings)
plt.grid(False)
plt.xlabel('item')
plt.ylabel('user')
plt.title('Rate Matrix')

In [1]:
import pandas as pd
df_ratings = pd.read_csv('./data/movie/linked_user_rating.csv',engine='python', thousands=',')

In [2]:
df_ratings

,userId,rating,title,time
0,1,1.0,Braveheart,2015-03-09 22:52:09
1,1,5.0,Star Trek,2015-03-09 22:51:04
2,1,4.0,Memento,2015-03-09 23:03:48
3,1,5.0,Harry Potter and the Half-Blood Prince,2015-03-09 23:02:19
4,1,4.0,The Breakfast Club,2015-03-09 23:02:28
5,1,5.0,Harry Potter and the Deathly Hallows: Part 1,2015-03-09 23:02:13
6,1,2.5,The Hunger Games,2015-03-09 23:10:47
7,1,5.0,The Art of Getting By,2015-03-09 22:50:24
8,1,5.0,The Perks of Being a Wallflower,2015-03-09 22:49:42
9,1,0.5,The Hobbit: An Unexpected Journey,2015-03-09 23:10:40
10,1,4.0,Django Unchained,2015-03-09 22:54:27
11,1,5.0,Whiplash,2015-03-09 22:48:56
12,1,5.0,The Godfather,2015-03-09 22:52:03
13,1,5.0,Ferris Bueller's Day Off,2015-03-09 22:53:13
14,1,4.5,The Sixth Sense,2015-03-09 22:48:20
15,1,4.5,The Basketball Diaries,2015-03-09 23:07:15
16,1,5.0,The Godfather: Part II,2015-03-09 22:52:26
17,1,4.0,Fight Club,2015-03-09 22:53:21
18,1,5.0,Iron Man,2015-03-09 22:51:42
19,1,4.0,The Dark Knight,2015-03-09 23:00:07
20,1,5.0,Sherlock Holmes: A Game of Shadows,2015-03-09 23:10:18
21,1,5.0,Dead Poets Society,2015-03-09 22:52:36
22,1,5.0,Donnie Darko,2015-03-09 22:50:34
23,1,5.0,Igby Goes Down,2015-03-09 22:49:57
24,1,4.0,Batman Begins,2015-03-09 23:00:05
25,1,3.5,Superbad,2015-03-09 22:48:33
26,7,1.0,Hancock,2017-02-05 00:19:35
27,7,3.0,Harry Potter and the Order of the Phoenix,2017-02-05 00:16:27
28,7,4.5,Fight Club,2017-02-05 00:13:22
29,7,3.0,The 40 Year Old Virgin,2017-02-05 00:15:58
...,...,...,...,...
8908400,270894,2.0,Psycho,2014-12-29 02:48:00
8908401,270894,4.0,Se7en,2014-12-29 02:37:10
8908402,270894,1.5,Contact,2014-12-29 02:48:51
8908403,270894,5.0,Alien,2014-12-29 02:36:43
8908404,270894,2.5,Children of Men,2014-12-29 02:46:50
8908405,270894,0.5,The Bling Ring,2014-12-29 02:42:55
8908406,270894,3.0,Groundhog Day,2014-12-29 02:46:16
8908407,270894,2.0,Thank You for Smoking,2014-12-29 02:35:07
8908408,270894,5.0,The Matrix,2014-12-29 02:46:11
8908409,270894,3.5,The American,2014-12-29 02:39:29
8908410,270894,1.0,Night of the Living Dead,2014-12-29 02:51:40
8908411,270894,4.0,Under the Skin,2014-12-29 02:38:15
8908412,270894,1.5,Rear Window,2014-12-29 02:36:41
8908413,270894,3.5,Planet of the Apes,2014-12-29 02:47:00
8908414,270894,2.0,In the Valley of Elah,2014-12-29 02:45:09
8908415,270894,4.0,The Exorcist,2014-12-29 02:40:52
8908416,270894,2.0,The Conversation,2014-12-29 02:52:59
8908417,270894,1.5,Oldboy,2014-12-29 02:41:16
8908418,270894,3.0,No Country for Old Men,2014-12-29 02:54:18
8908419,270894,0.5,Cocoon,2014-12-29 02:49:14
8908420,270894,3.5,At Close Range,2014-12-29 02:44:19
8908421,270894,0.5,Airplane!,2014-12-29 02:51:34
8908422,270894,2.5,Source Code,2014-12-29 02:56:09
8908423,270894,1.5,Amadeus,2014-12-29 02:48:47
8908424,270894,1.5,The Hunt for Red October,2014-12-29 02:52:02
8908425,270894,3.5,The Abyss,2014-12-29 02:46:40
8908426,270894,2.0,Leon: The Professional,2014-12-29 02:42:46
8908427,270894,5.0,"After Dark, My Sweet",2014-12-29 02:44:01
8908428,270894,4.0,Terminator 2: Judgment Day,2014-12-29 02:40:33
8908429,270894,3.0,Louis C.K.: Live at the Beacon Theater,2014-12-29 02:52:37

In [3]:
del df_ratings["time"]

In [4]:
df_ratings

         userId  rating                                         title
0             1     1.0                                    Braveheart
1             1     5.0                                     Star Trek
2             1     4.0                                       Memento
3             1     5.0        Harry Potter and the Half-Blood Prince
4             1     4.0                            The Breakfast Club
5             1     5.0  Harry Potter and the Deathly Hallows: Part 1
6             1     2.5                              The Hunger Games
7             1     5.0                         The Art of Getting By
8             1     5.0               The Perks of Being a Wallflower
9             1     0.5             The Hobbit: An Unexpected Journey
10            1     4.0                              Django Unchained
11            1     5.0                                      Whiplash
12            1     5.0                                 The Godfather
13            1     5.0                      Ferris Bueller's Day Off
14            1     4.5                               The Sixth Sense
15            1     4.5                        The Basketball Diaries
16            1     5.0                        The Godfather: Part II
17            1     4.0                                    Fight Club
18            1     5.0                                      Iron Man
19            1     4.0                               The Dark Knight
20            1     5.0            Sherlock Holmes: A Game of Shadows
21            1     5.0                            Dead Poets Society
22            1     5.0                                  Donnie Darko
23            1     5.0                                Igby Goes Down
24            1     4.0                                 Batman Begins
25            1     3.5                                      Superbad
26            7     1.0                                       Hancock
27            7     3.0     Harry Potter and the Order of the Phoenix
28            7     4.5                                    Fight Club
29            7     3.0                        The 40 Year Old Virgin
...         ...     ...                                           ...
8908400  270894     2.0                                        Psycho
8908401  270894     4.0                                         Se7en
8908402  270894     1.5                                       Contact
8908403  270894     5.0                                         Alien
8908404  270894     2.5                               Children of Men
8908405  270894     0.5                                The Bling Ring
8908406  270894     3.0                                 Groundhog Day
8908407  270894     2.0                         Thank You for Smoking
8908408  270894     5.0                                    The Matrix
8908409  270894     3.5                                  The American
8908410  270894     1.0                      Night of the Living Dead
8908411  270894     4.0                                Under the Skin
8908412  270894     1.5                                   Rear Window
8908413  270894     3.5                            Planet of the Apes
8908414  270894     2.0                         In the Valley of Elah
8908415  270894     4.0                                  The Exorcist
8908416  270894     2.0                              The Conversation
8908417  270894     1.5                                        Oldboy
8908418  270894     3.0                        No Country for Old Men
8908419  270894     0.5                                        Cocoon
8908420  270894     3.5                                At Close Range
8908421  270894     0.5                                     Airplane!
8908422  270894     2.5                                   Source Code
8908423  270894     1.5                                       Amadeus
8908424  270894     1.5                      The Hunt for Red October
8908425  270894     3.5                                     The Abyss
8908426  270894     2.0                        Leon: The Professional
8908427  270894     5.0                          After Dark, My Sweet
8908428  270894     4.0                    Terminator 2: Judgment Day
8908429  270894     3.0        Louis C.K.: Live at the Beacon Theater

[8908430 rows x 3 columns]

In [5]:
df_new = df_ratings.copy()

In [8]:
df_new["Rating"] = df_new["rating"]

In [9]:
df_new

         userId  rating                                         title  Rating
0             1     1.0                                    Braveheart     1.0
1             1     5.0                                     Star Trek     5.0
2             1     4.0                                       Memento     4.0
3             1     5.0        Harry Potter and the Half-Blood Prince     5.0
4             1     4.0                            The Breakfast Club     4.0
5             1     5.0  Harry Potter and the Deathly Hallows: Part 1     5.0
6             1     2.5                              The Hunger Games     2.5
7             1     5.0                         The Art of Getting By     5.0
8             1     5.0               The Perks of Being a Wallflower     5.0
9             1     0.5             The Hobbit: An Unexpected Journey     0.5
10            1     4.0                              Django Unchained     4.0
11            1     5.0                                      Whiplash     5.0
12            1     5.0                                 The Godfather     5.0
13            1     5.0                      Ferris Bueller's Day Off     5.0
14            1     4.5                               The Sixth Sense     4.5
15            1     4.5                        The Basketball Diaries     4.5
16            1     5.0                        The Godfather: Part II     5.0
17            1     4.0                                    Fight Club     4.0
18            1     5.0                                      Iron Man     5.0
19            1     4.0                               The Dark Knight     4.0
20            1     5.0            Sherlock Holmes: A Game of Shadows     5.0
21            1     5.0                            Dead Poets Society     5.0
22            1     5.0                                  Donnie Darko     5.0
23            1     5.0                                Igby Goes Down     5.0
24            1     4.0                                 Batman Begins     4.0
25            1     3.5                                      Superbad     3.5
26            7     1.0                                       Hancock     1.0
27            7     3.0     Harry Potter and the Order of the Phoenix     3.0
28            7     4.5                                    Fight Club     4.5
29            7     3.0                        The 40 Year Old Virgin     3.0
...         ...     ...                                           ...     ...
8908400  270894     2.0                                        Psycho     2.0
8908401  270894     4.0                                         Se7en     4.0
8908402  270894     1.5                                       Contact     1.5
8908403  270894     5.0                                         Alien     5.0
8908404  270894     2.5                               Children of Men     2.5
8908405  270894     0.5                                The Bling Ring     0.5
8908406  270894     3.0                                 Groundhog Day     3.0
8908407  270894     2.0                         Thank You for Smoking     2.0
8908408  270894     5.0                                    The Matrix     5.0
8908409  270894     3.5                                  The American     3.5
8908410  270894     1.0                      Night of the Living Dead     1.0
8908411  270894     4.0                                Under the Skin     4.0
8908412  270894     1.5                                   Rear Window     1.5
8908413  270894     3.5                            Planet of the Apes     3.5
8908414  270894     2.0                         In the Valley of Elah     2.0
8908415  270894     4.0                                  The Exorcist     4.0
8908416  270894     2.0                              The Conversation     2.0
8908417  270894     1.5                                        Oldboy     1.5
8908418  270894     3.0                        No Country for Old Men     3.0
8908419  270894     0.5                                        Cocoon     0.5
8908420  270894     3.5                                At Close Range     3.5
8908421  270894     0.5                                     Airplane!     0.5
8908422  270894     2.5                                   Source Code     2.5
8908423  270894     1.5                                       Amadeus     1.5
8908424  270894     1.5                      The Hunt for Red October     1.5
8908425  270894     3.5                                     The Abyss     3.5
8908426  270894     2.0                        Leon: The Professional     2.0
8908427  270894     5.0                          After Dark, My Sweet     5.0
8908428  270894     4.0                    Terminator 2: Judgment Day     4.0
8908429  270894     3.0        Louis C.K.: Live at the Beacon Theater     3.0

[8908430 rows x 4 columns]

In [11]:
del df_new["rating"]

In [12]:
from surprise import Dataset
from surprise import NormalPredictor
from surprise import Reader
from surprise.model_selection import cross_validate
import pandas as pd
import numpy as np

In [25]:
# A reader is still needed but only the rating_scale param is requiered.
reader = Reader(rating_scale=(3, 5))

# The columns must correspond to user id, item id and ratings (in that order).
data = Dataset.load_from_df(df_nn[['userId', 'title', 'Rating']], reader)

In [15]:
import surprise

In [2]:
import surprise

In [26]:
from surprise.model_selection import KFold

bsl_options = {
    'method': 'als',
    'n_epochs': 5,
    'reg_u': 12,
    'reg_i': 5
}
algo = surprise.BaselineOnly(bsl_options)

np.random.seed(0)
acc = np.zeros(3)
cv = KFold(3)
for i, (trainset, testset) in enumerate(cv.split(data)):
    algo.fit(trainset)
    predictions = algo.test(testset)
    acc[i] = surprise.accuracy.rmse(predictions, verbose=True)
acc.mean()

Estimating biases using als...
RMSE: 0.5482
Estimating biases using als...
RMSE: 0.5480
Estimating biases using als...
RMSE: 0.5479

0.5480433395667622